/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iOpenOceanSol from "./IOpenOcean.sol";
export type { iOpenOceanSol };
export type { IDiamondCut } from "./IDiamondCut";
export type { IDiamondLoupe } from "./IDiamondLoupe";
export type { IERC165 } from "./IERC165";
export type { IERC173 } from "./IERC173";
export type { IERC20 } from "./IERC20";
export type { ILiFi } from "./ILiFi";
