/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iOpenOceanSol from "./IOpenOcean.sol";
export { IDiamondCut__factory } from "./IDiamondCut__factory";
export { IDiamondLoupe__factory } from "./IDiamondLoupe__factory";
export { IERC165__factory } from "./IERC165__factory";
export { IERC173__factory } from "./IERC173__factory";
