/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface LibBridgeManagerInterface extends utils.Interface {
  functions: {
    "getSubscribeDestinationCalldata(address,uint256,uint8,uint256,address,uint256,address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getSubscribeDestinationCalldata"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getSubscribeDestinationCalldata",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSubscribeDestinationCalldata",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LibBridgeManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibBridgeManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSubscribeDestinationCalldata(
      user: PromiseOrValue<string>,
      subManagerId: PromiseOrValue<BigNumberish>,
      subscriptionId: PromiseOrValue<BigNumberish>,
      paymentChainId: PromiseOrValue<BigNumberish>,
      paymentToken: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      referral: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getSubscribeDestinationCalldata(
    user: PromiseOrValue<string>,
    subManagerId: PromiseOrValue<BigNumberish>,
    subscriptionId: PromiseOrValue<BigNumberish>,
    paymentChainId: PromiseOrValue<BigNumberish>,
    paymentToken: PromiseOrValue<string>,
    price: PromiseOrValue<BigNumberish>,
    referral: PromiseOrValue<string>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getSubscribeDestinationCalldata(
      user: PromiseOrValue<string>,
      subManagerId: PromiseOrValue<BigNumberish>,
      subscriptionId: PromiseOrValue<BigNumberish>,
      paymentChainId: PromiseOrValue<BigNumberish>,
      paymentToken: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      referral: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getSubscribeDestinationCalldata(
      user: PromiseOrValue<string>,
      subManagerId: PromiseOrValue<BigNumberish>,
      subscriptionId: PromiseOrValue<BigNumberish>,
      paymentChainId: PromiseOrValue<BigNumberish>,
      paymentToken: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      referral: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSubscribeDestinationCalldata(
      user: PromiseOrValue<string>,
      subManagerId: PromiseOrValue<BigNumberish>,
      subscriptionId: PromiseOrValue<BigNumberish>,
      paymentChainId: PromiseOrValue<BigNumberish>,
      paymentToken: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      referral: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
